name: Build Humble

on:
  workflow_dispatch:
  schedule:
    - cron: "03 1 * * *"

jobs:
  binary:
    uses: ./.github/workflows/reusable-ici.yaml
    with:
      ros_distro: humble
      ros_repo: main
      upstream_workspace: ros2_net_ft_driver.humble
      ref_for_scheduled_build: humble
      before_install_target_dependencies: |
        sudo apt-get -qq update && sudo apt-get install -y pkg-config libasio-dev libcurlpp-dev libcurl4-openssl-dev
